apiVersion: skaffold/v4beta3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: anuj2110/ticketing-auth-service
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
  
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
